
export const userRegistr = {
    REGISTER_REQUEST : 'REGISTER_REQUEST',
    REGISTER_SUCCESS : 'REGISTER_SUCCESS',
    REGISTER_FAILURE : 'REGISTER_FAILURE',
    REGISTERED : 'REGISTERED'
};

export const userLogin = {
    LOGIN_REQUEST : 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS : 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE : 'USERS_LOGIN_FAILURE'
};

export const ProductById = {
    PRODUCT_BY_ID_REQUEST : 'PRODUCT_BY_ID_REQUEST',
    PRODUCT_BY_ID_SUCCESS : 'PRODUCT_BY_ID_SUCCESS',
    PRODUCT_BY_ID_FAILURE : 'PRODUCT_BY_ID_FAILURE'
};
export const AllProduct = {
    FETCH_PRODUCTS_REQUEST : 'FETCH_PRODUCTS_REQUEST',
    FETCH_PRODUCTS_SUCCESS :'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE : 'FETCH_PRODUCTS_FAILURE'

}
export const CreateProduct = {
    CREATE_PRODUCT_REQUEST : 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_SUCCESS : 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILURE : 'CREATE_PRODUCT_FAILURE'
}